# Generated by Django 2.2 on 2019-09-20 10:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultsMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_metadata', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('search_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='feed.SearchResultsMeta')),
            ],
        ),
    ]
